version: "3"
services:
    nats:
        image: nats:latest
        container_name: nats
        ports:
            - "4222:4222"
            - "8222:8222"
    db:
        image: mysql:5.7.6
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_DATABASE: d2d
            MYSQL_ROOT_PASSWORD: password
